#!/usr/bin/env python3
import re
import subprocess
import requests
from urllib.parse import urlparse
import sys

# sigint-hombre v1
# Author: John Page — malvuln (aka hyp3rlinx)
# Copyright (c) 2026 John Page
#================================================================
# URLhaus → Suricata Rule Generator (HTTP, TLS/SNI, DNS)
#================================================================
#  - Downloads URLhaus threat indicators at runtime
#  - Generates original, derived Suricata detection rules
#    (does NOT mirror or redistribute the feed/database)
#  - Produces detection logic for:
#       * HTTP  (URL + path matching)
#       * TLS   (HTTPS detection via SNI)
#       * DNS   (domain lookup coverage)
#  - Skips trusted domains to reduce noise/false positives
#
#  Output File:
#     /opt/so/rules/suricata/siginthombre.rules
#
#  Deployment Notice:
#     Suricata rules generated by this tool should be validated
#     before production deployment. No warranty or liability is
#     provided. The author is not responsible for any damages,
#     use at your own risk.
#
#  Usage (cron example — run once per hour):
#         0 * * * * /usr/local/bin/siginthombre.py
#
#  Compatibility Statement:
#     Built for compatibility with the Security Onion platform, but
#     independently developed. Not affiliated with, endorsed by, or
#     supported by Security Onion LLC.
#     Security Onion is a trademark of Security Onion LLC.
#
#  Data Source & Trademark Acknowledgment:
#     Threat feed indicators are consumed at runtime from the
#     public URLhaus feed, a service operated by abuse.ch.
#     Indicators are used only to generate derived detection rules and
#     are NOT redistributed as a database or feed mirror.
#
#     abuse.ch is a trademark of abuse.ch and is acknowledged as such.
#     No third-party databases, malware samples, or proprietary
#     content are redistributed by this project.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  This software is provided "AS-IS", WITHOUT WARRANTY of any kind.
#=================================================================

FEED_URL = "https://urlhaus.abuse.ch/downloads/text/"
RULE_FILE = "/opt/so/rules/suricata/siginthombre.rules" 
##OLD  "/opt/so/rules/nids/suri/siginthombre.rules"

#Try reduce noise
trusted_domains = [
    "bitbucket.org", "bitbucket.com", "github.com", "google.com",
    "dropbox.com", "googleapis.com", "jsdelivr.net", "live.com",
    "constantcontact.com", "archive.org", "githubusercontent.com",
    "dropboxusercontent.com"
]

#Suricata ID (SID)
SID_HTTP = 9100000
SID_SNI = 9200000
SID_DNS = 9300000

def normalize_host(host):
    host = host.strip().lower()            
    host = host.rstrip(".")               
    host = re.sub(r"\s+", "", host) 
    if re.match(r"^\d{1,3}(\.\d{1,3}){3}$", host):
        parts = host.split(".")
        host = ".".join(str(int(p)) for p in parts)
    return host


def is_trusted(host):
    for d in trusted_domains:
        if host == d or host.endswith("." + d):
            return True
    return False


def main():
    try:
        print("[*] Downloading URLhaus feed...")
        resp = requests.get(FEED_URL, timeout=30)
        resp.raise_for_status()
        feed = resp.text
        if not feed.strip():
            print("[!] Feed is empty. Exiting.")
            sys.exit(1)
        print(f"[+] Feed downloaded. Size: {len(feed)} bytes")
    except Exception as e:
        print(f"[!] Failed to download feed: {e}", str(e))
        sys.exit(1)

    sid_http = SID_HTTP
    sid_sni = SID_SNI
    sid_dns = SID_DNS

    processed_http = set()
    processed_https_sni = set()
    processed_dns = set()

    with open(RULE_FILE, "w") as f:
        f.write("# === BEGIN URLHAUS COMBINED RULES ===\n")
        f.write(f"# Generated: {__import__('datetime').datetime.utcnow().isoformat()}Z\n\n")

        for line in feed.splitlines():
            url = line.strip()
            if not url or url.startswith("#") or "urlhaus.abuse.ch" in url:
                continue

            if "://" not in url:
                continue

            parsed = urlparse(url)
            proto = parsed.scheme
            host = normalize_host(parsed.hostname or "")
            path = parsed.path or "/"
            
            #Use explicit port if present, otherwise allow any port for better HTTP coverage
            if proto == "http":
                if parsed.port:
                    port = parsed.port
                else:
                    port = "any"
            else:
                port = parsed.port

            #Prepare safe strings for rule writing
            safe_url = url.replace("\\", "\\\\").replace("\"", "\\\"")
            safe_path = path.rstrip().replace("\\", "\\\\").replace("\"", "\\\"")

            if proto == "http":
                norm_host = normalize_host(host)
                if is_trusted(norm_host):
                    continue

                key = (norm_host, path)
                if key in processed_http:
                    continue
                processed_http.add(key)

                safe_host = norm_host.replace("\\", "\\\\").replace("\"", "\\\"")

                if re.match(r"^\d{1,3}(\.\d{1,3}){3}$", norm_host):
                    f.write(f'alert http any any -> {norm_host} {port} (msg:"[URLhaus] Malicious HTTP request to IP: {safe_url}"; flow:to_server,established; http.uri; content:"{safe_path}"; nocase; sid:{sid_http}; rev:1; classtype:trojan-activity; metadata:service http, urlhaus;)\n')
                else:
                    f.write(f'alert http any any -> any {port} (msg:"[URLhaus] Malicious HTTP URL: {safe_url}"; flow:to_server,established; http.host; content:"{safe_host}"; http.uri; content:"{safe_path}"; nocase; sid:{sid_http}; rev:1; classtype:trojan-activity; metadata:service http, urlhaus;)\n')
                sid_http += 1

            elif proto == "https":
                norm_host = normalize_host(host)
                if is_trusted(norm_host):
                    continue
                if norm_host in processed_https_sni:
                    continue
                processed_https_sni.add(norm_host)

                safe_host = norm_host.replace("\\", "\\\\").replace("\"", "\\\"")

                f.write(f'alert tls any any -> any 443 (msg:"[URLhaus] Malicious TLS SNI: {safe_host}"; tls.sni; content:"{safe_host}"; sid:{sid_sni}; rev:1; classtype:trojan-activity; metadata:service tls, urlhaus;)\n')
                sid_sni += 1

            #DNS Coverage
            norm_host = normalize_host(host)
            
            #If feed has a trusted domain with trailing dot, is_trusted(norm_host) might fail to match
            norm_host = norm_host.rstrip(".")
            if is_trusted(norm_host):
                continue
            
            # DNS never queries raw IPs
            if re.match(r"^\d{1,3}(\.\d{1,3}){3}$", norm_host):
                continue
            
            if norm_host in processed_dns:
                continue

            processed_dns.add(norm_host)
            safe_host = norm_host.replace("\\", "\\\\").replace("\"", "\\\"")

            f.write(f'alert dns any any -> any any (msg:"[URLhaus] Malicious DNS query for domain: {safe_host}"; dns.query; content:"{safe_host}"; nocase; sid:{sid_dns}; rev:1; classtype:trojan-activity; metadata:service dns, urlhaus;)\n')
            sid_dns += 1

        f.write("\n# === END URLHAUS COMBINED RULES ===\n")

    print(f"[+] Rules written to: {RULE_FILE}")
    print("[*] Restarting Suricata rules...")
    try:
        subprocess.run(["sudo", "so-suricata-restart", "--force"], check=True)
        print("[+] Suricata restarted successfully.")
    except subprocess.CalledProcessError as e:
        print("[!] Failed to restart Suricata rules. Please restart manually.", str(e))

if __name__ == "__main__":
    main()

